[package]
name = "rv32ima-oxide"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
#pprof = { version = "0.11", features = ["flamegraph"] }


[profile.release]
debug = true
